### PR TITLE
update express-sms-autoresponder to Typescript

### PR DESCRIPTION
**Pull request by lucasassisrosa**
https://github.com/team-telnyx/demo-node-telnyx/blob/bc762245ce49449ee1612564ee0e3b143098d872/express-sms-autoresponder/README.md#setup-localhost-app

### CODE REVIEW

**Review by DRS90 — COMMENTED** [review]
I get this error when I try to run the sms-autoresponder locally
Screenshot 2024-10-11 at 11 18 09

**Comment by lucasassisrosa** [comment]
> I get this error when I try to run the sms-autoresponder locally Screenshot 2024-10-11 at 11 18 09

thanks! probably some deps missing. Let me fix

**Review by BueTelnyx — APPROVED** [review]
Got this to work!
Seems like a quick and easy demo, super powerful to sending text messages like this.
However one code change I suggest is have the port pull for the environment variables. Like `const port = process.env.PORT || 5000`

**Comment by lucasassisrosa** [comment]
> I get this error when I try to run the sms-autoresponder locally Screenshot 2024-10-11 at 11 18 09

fixed this by bumping telnyx package to `2.0.0-beta.3`

https://github.com/team-telnyx/telnyx-node/releases/tag/v2.0.0-beta.3

**Comment by lucasassisrosa** [comment]
> Got this to work! Seems like a quick and easy demo, super powerful to sending text messages like this. However one code change I suggest is have the port pull for the environment variables. Like `const port = process.env.PORT || 5000`

thanks! I added this line to pull port from envs. Also changed default port to be 8000 since 5000 is often in use

**Pull request merged**
